server:
  port: 8081

spring:
  application:
  name: otel-instrumentation-a
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5424/alarms
    username: alarms
    password: alarms
  data:
    redis:
      host: localhost
      port: 6379
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace: otel-instrumentation
    local-datacenter: datacenter1

kafka:
  bootstrapServers: localhost:29092
  producerTopic: test.events

otel:
  traces:
    exporter: logging
  metrics:
    exporter: none
  logs:
    exporter: none

logging:
  level:
    io:
      codifica: DEBUG
